---
title : Diagramme de classes TP 4
---

classDiagram 
	namespace UI {
		class Menu {
			+handleMenu(List~MenuEntry~ entries) void
		}

		class MenuEntry {
			<<interface>>
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class ExitEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class AddGameEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class RemoveGameEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}
		
		class RecommendOneGameEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class RecommendByPlayerCountEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class ListAllGamesEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class SummaryEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class UndoLastActionEntry {
			+handle(MenuInterface UI, GameCollectionDao dao) void
			+label() String
		}

		class MenuFormatter {
            +displayMessage(String message) void
            +displayMessage(String format, Object... args) void
            +displayGames(List~BoardGame~ games) void
            +getUserInput(String message) String
            +displayMenu(List~MenuEntry~ entries) void
            +getGameTitle() String
            +getNumberFromUser(String message) Int
            +getGameCategory() String
        }

        class MenuInterface {
            <<interface>>
            +displayMessage(String message) void
            +displayMessage(String format, Object... args) void
            +displayGames(List~BoardGame~ games) void
            +getUserInput(String message) String
            +displayMenu(List~MenuEntry~ entries) void
            +getGameTitle() String
            +getNumberFromUser(String message) Int
            +getGameCategory() String
        }

		class TournamentEntry {
            -formats List~TournamentFormat~
            +handle(MenuInterface UI, GameCollectionDao dao) Void
            +label() String
        }

		class TournamentFormatter {
            %% Récupère les inputs utilisateurs d'un match %%
            +getWinnerFromUser() void
            %% Affichage du gagnant %%
            +displayWinner() void
            %% Affichage des gagnants %%
            +displayAllScores() void
        }
	}

	namespace Services {
		class DaoFactory {
			+create(String filename) GameCollectionDao
		}

		class MenuFactory {
			+create() List~MenuEntry~
		}

		class DateGestion {
			+isWeekEnd(int weekDay) Boolean
			+getDate() Calendar
			+getWeekDay() Int
		}

		class BoardGameVerificator {
			+isADuplicate(String title, GameCollectionDao dao) Boolean
			+isValidString(String input) Boolean
			+isValidNumber(String input) Boolean
			+isEmptyList(List~?~ list) Boolean
		}

		class RecommendationStrategy {
			<<interface>>
			+getNRandomGames(Int numberOfGames, GameCollectionDao) List~BoardGame~
		}

		class RandomNElementsStrategy {
			+getNRandomGames(Int numberOfGames, GameCollectionDao) List~BoardGame~
		}

		class LastNElementsStrategy {
			+getNRandomGames(Int numberOfGames, GameCollectionDao) List~BoardGame~
		}

		class FirstNElementsStrategy {
			+getNRandomGames(Int numberOfGames, GameCollectionDao) List~BoardGame~
		}

		class EntryService {

		}

		class TournamentFormat {
            <<interface>>
            +label() String
            +playMatch() void %% appel à tournamentFormatter %%
            +attributePoints() void
            +playTournament() List~Player~ %% itère sur les playMatch et donne les scores finaux à tournamentEntry %%
        }

        class KingOfTheHillFormat {
            +label() String
            +playMatch() void
            +attributePoints() void
            +playTournament() List~Player~
        }
        class ChampionshipFormat {
            +label() String
            +playMatch() void
            +attributePoints() void
            +playTournament() List~Player~
        }
	}

	namespace Data {
		class BoardGame {
			+title String
			+minPlayers int
			+maxPlayers int
			+category String
		}

		class Command {
			<<interface>>
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class RemoveGameCommand {
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class AddGameCommand {
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class GameCollectionDao {
			<<interface>>
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoJson {
			-filename String
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoCsv {
			-filename String
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoRam {
			-games List~BoardGame~
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class HistoryDao {
			<<interface>>
			+saveModification(Command command) void
			+findAll() List~Command~
			+removeLast() Command
		}

		class HistoryDaoRam {
			+saveModification(Command command) void
			+findAll() List~Command~
			+removeLast() Command
		}

		class Player {
            +name String
            +numberOfWins int
            +points int
        }
	}

	namespace main {
		class Main {
			+receiveArguments(String[] arguments) String
			+launch() void
			+verifyGivenFile(String filename) void
		}

	}

	%% Liens entre les classes

	Main --> MenuFactory: Création de la liste d'entrées du Menu
	Main --> DaoFactory : Création de la DAO
	Main --> Menu : Transmission au menu	

	DaoFactory --> GameCollectionDao : instancie

	GameCollectionDao <|.. GameCollectionDaoCsv
	GameCollectionDao <|.. GameCollectionDaoRam
	GameCollectionDao <|.. GameCollectionDaoJson
	GameCollectionDao --> BoardGame : stocke les jeux

	MenuFactory --> MenuEntry : instancie
	MenuFactory --> DateGestion : utilises les vérification horodatées
	MenuFactory --> HistoryDao : affectes à certaines entrées du menu l'historique

	MenuEntry <|.. ExitEntry
	MenuEntry <|.. AddGameEntry
	MenuEntry <|.. RemoveGameEntry
	MenuEntry <|.. RecommendOneGameEntry
	MenuEntry <|.. RecommendByPlayerCountEntry
	MenuEntry <|.. ListAllGamesEntry
	MenuEntry <|.. SummaryEntry
	MenuEntry <|.. TournamentEntry

	HistoryDao <|.. HistoryDaoRam
	HistoryDao --> Command : stocke des commandes

	Menu --> MenuInterface : utilises pour l'affichage
	Menu --> MenuEntry : associe le choix de l'utilisateur à la bonne entrée

	MenuInterface <|.. MenuFormatter

	MenuEntry --> GameCollectionDao : utilises la dao pour stocker les jeux
	MenuEntry --> MenuInterface : utilises le formatter pour afficher
	MenuEntry --> TournamentFormatter : utilises le formatter pour afficher

	AddGameEntry --> HistoryDao : log l'ajout
	RemoveGameEntry --> HistoryDao : log le retrait
	RecommendOneGameEntry --> RecommendationStrategy : utilises une stratégie de recommendation
	SummaryEntry --> RecommendationStrategy : utilises une stratégie de recommendation
	UndoLastActionEntry --> HistoryDao : enregistre l'annulation de la dernière action

	Command <|.. RemoveGameCommand
	Command <|.. AddGameCommand
	Command --> GameCollectionDao : répercute l'historique sur la DAO

	RecommendationStrategy <|.. FirstNElementsStrategy
	RecommendationStrategy <|.. LastNElementsStrategy
	RecommendationStrategy <|.. RandomNElementsStrategy
	RecommendationStrategy --> GameCollectionDao : utilises

	TournamentFormat <|.. KingOfTheHillFormat
	TournamentFormat <|.. ChampionshipFormat