---
title : Diagramme de classes TP 4
---

classDiagram 
	namespace Data {
		class BoardGame {
			+title String
			+minPlayers int
			+maxPlayers int
			+category String
		}

		class Command {
			<<interface>>
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class RemoveGameCommand {
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class AddGameCommand {
			+restore(GameCollectionDao dao) void
			+getModifiedGame() BoardGame
		}

		class GameCollectionDao {
			<<interface>>
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoJson {
			-filename String
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoCsv {
			-filename String
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class GameCollectionDaoRam {
			-games List~BoardGame~
			+save(BoardGame game) boolean
			+findAll() List~BoardGame~
			+delete(String title)
			+findByNumberOfPlayers(Int numberOfPlayers)
			+findByTitle(String title)
			+findAllInAlphabeticalOrder(List~BoardGame~ games) List~BoardGame~
		}

		class HistoryDao {
			<<interface>>
			+saveModification(Command command) void
			+findAll() List~Command~
			+removeLast() Command
		}

		class HistoryDaoRam {
			+saveModification(Command command) void
			+findAll() List~Command~
			+removeLast() Command
		}

		class Player {
            +name String
            +numberOfWins int
            +points int
			+getName() String
			+getNumberOfWins() int
			+getPoints() int
			+setName() void
			+setNumberOfWins(int numberOfWins) void
			+setPoints(int points) void
        }
	}
	
	namespace Services {
		class GamesDaoFactory {
			+create(String filename) GameCollectionDao$
		}

		class MenuFactory {
			+create() List~MenuEntry~$
		}

		class TournamentFormatFactory {
			+create(MenuInterface UI) List~TournamentFormat~$
		}

		class DateGestion {
			+isWeekEnd(int weekDay) Boolean
			+getDate() Calendar
			+getWeekDay() Int
		}

		class BoardGameVerificator {
			+isADuplicate(String title, GameCollectionDao dao) Boolean$
			+isValidString(String input) Boolean$
			+isValidNumber(String input) Boolean$
			+isEmptyList(List~?~ list) Boolean$
		}

		class RecommendationStrategy {
			<<interface>>
			+getNRandomGames(Int numberOfGames, List~BoardGame~) List~BoardGame~
		}

		class RandomNElementsStrategy {
			+getNRandomGames(Int numberOfGames, List~BoardGame~) List~BoardGame~
		}

		class LastNElementsStrategy {
			+getNRandomGames(Int numberOfGames, List~BoardGame~) List~BoardGame~
		}

		class FirstNElementsStrategy {
			+getNRandomGames(Int numberOfGames, List~BoardGame~) List~BoardGame~
		}

		class EntryService~T, E~ {
			<<interface>>
        	+execute() Result~T, E~
		}

		class AddGameService {
			-gamesDao GameCollectionDao
			-historyDao HistroyDao
    		+addGame(BoardGame game) Result~Void, String~
		}

		class RemoveGameService {
			-gamesDao GameCollectionDao
			-historyDao HistroyDao
    		+removeGame(BoardGame game) Result~Void, String~
		}

        class RecommendOneGameService {
			-strategy RecommendationStrategy
    		+recommendOneGame(int numberOfPlayers, GameCollectionDao gamesDao) Result~BoardGame, String~
		}

		class RecommendByPlayerCountService {
			-GameCollectionDao gamesDao
    		+recommendByPlayerCount(int playerCount) Result~List~BoardGame~, String~
		}

		class ListAllGamesService {
			-gamesDao GameCollectionDao
    		+findAllGames() Result~List~BoardGame~, String~
		}

		class SummaryService {
			-gamesDao GameCollectionDao
    		+makeSummary() Result~List~BoardGame~, String~
		}

		class UndoLastActionService {
			-gamesDao GameCollectionDao
			-historyDao HistoryDao
			+undo() String
		}

		class TournamentService {
			+execute(MenuInterface UI) Result~List~Player~, String~
			-getPlayers(MenuInterfaceUI) List~Player~
			-getNumberOfParticipants(MenuInterface UI) int
			-getPlayerName(MenuInterface UI, int index) String
			-selectFormat(MenuInterface UI) TournamentFormat
			-playTournament(TournamentFormat format, List~Player~ players) List~Player~
			-sortResults(List~Player~ players) List~Player~
		}

		class Result~T, E~ {
			<<interface>>
			+isSuccess() boolean
			+value() T
			+error() E
		}

		class Success~T, E~ {
			<<record>>
			+value T
			+isSuccess() boolean
			+error() E
		}

		class Failure~T, E~ {
			<<record>>
			+error E
			+isSuccess() boolean
			+value() T
		}

		class TournamentFormat {
            <<interface>>
            +label() String
            +playMatch() void 
            +attributePoints() void
            +playTournament() List~Player~
			+setPlayers(List~Player~ players) void
        }

        class KingOfTheHillFormat {
            +label() String
            +playMatch() void
            +attributePoints() void
            +playTournament() List~Player~
			+setPlayers(List~Player~ players) void
        }
        class ChampionshipFormat {
            +label() String
            +playMatch() void
            +attributePoints() void
            +playTournament() List~Player~
			+setPlayers(List~Player~ players) void
        }
	}

	namespace UI {
		class MenuFormatter {
            +displayMessage(String message) void
            +displayMessage(String format, Object... args) void
            +displayGames(List~BoardGame~ games) void
			+displayGame(BoardGame game) void
            +getUserInput(String message) String
            +displayMenu(List~MenuEntry~ entries) void
            +getGameTitle() String
            +getNumberFromUser(String message) Int
            +getGameCategory() String
			+displayPlayers(List~Player~ players) void
        }

        class MenuInterface {
            <<interface>>
            +displayMessage(String message) void
            +displayMessage(String format, Object... args) void
            +displayGames(List~BoardGame~ games) void
            +displayGame(BoardGame game) void
            +getUserInput(String message) String
            +displayMenu(List~MenuEntry~ entries) void
            +getGameTitle() String
            +getNumberFromUser(String message) Int
            +getGameCategory() String
			+displayPlayers(List~Player~ players) void
        }

		class Menu {
			+handleMenu(List~MenuEntry~ entries) void
		}

		class MenuEntry {
			<<interface>>
			+handle(MenuInterface UI) void
			+label() String
		}

		class ExitEntry {
			+handle(MenuInterface UI) void
			+label() String
		}

		class AddGameEntry {
			<<record>>
			+label String
			+service AddGameService
			+handle(MenuInterface UI) void
		}

		class RemoveGameEntry {
			<<record>>
			+label String
			+service RemoveGameService
			+handle(MenuInterface UI) void
		}
		
		class RecommendOneGameEntry {
			<<record>>
			+label String
			+gamesDao GameCollectionDao
			+service RecommendOneGameService
			+handle(MenuInterface UI) void
		}

		class RecommendByPlayerCountEntry {
			<<record>>
			+label String
			+service RecommendByPlayerCountService
			+handle(MenuInterface UI, GameCollectionDao dao) void
		}

		class ListAllGamesEntry {
			<<record>>
			+label String
			+service ListAllGamesService
			+handle(MenuInterface UI) void
		}

		class SummaryEntry {
			<<record>>
			+label String
			+service SummaryService
			+handle(MenuInterface UI) void
		}

		class UndoLastActionEntry {
			<<record>>
			+label String
			+service UndoLastActionService
			+handle(MenuInterface UI) void
		}

		class TournamentEntry {
			<<record>>
			+label String
			+service TournamentService
            +handle(MenuInterface UI) void
        }
	}

	class Main {
		+receiveArguments(String[] arguments) String
		+launch() void
		+verifyGivenFile(String filename) void
	}

	%% Liens entre les classes

	Main --> MenuFactory: Create the list of avilable menu entries
	Main --> HistoryDao: Instantiate one implementation of History
	Main --> GamesDaoFactory : Create GameCollectionDao
	Main --> Menu : relays to Menu

	GamesDaoFactory --> GameCollectionDao : instantiate GamesCollectionDao

	GameCollectionDao <|.. GameCollectionDaoCsv
	GameCollectionDao <|.. GameCollectionDaoRam
	GameCollectionDao <|.. GameCollectionDaoJson
	GameCollectionDao --> BoardGame : provides a way to save games

	MenuFactory --> MenuEntry : instantiate
	MenuFactory --> DateGestion : uses timed verifications
	MenuFactory --> HistoryDao : binds to some entries

	MenuEntry <|.. ExitEntry : implements
	MenuEntry <|.. AddGameEntry : implements
	MenuEntry <|.. RemoveGameEntry : implements
	MenuEntry <|.. RecommendOneGameEntry : implements
	MenuEntry <|.. RecommendByPlayerCountEntry : implements
	MenuEntry <|.. ListAllGamesEntry : implements
	MenuEntry <|.. SummaryEntry : implements
	MenuEntry <|.. TournamentEntry : implements
	MenuEntry <|.. UndoLastActionEntry : implements

	HistoryDao <|.. HistoryDaoRam : implements
	HistoryDao --> Command : saves commands

	Menu --> MenuInterface : uses to display
	Menu --> MenuEntry : bind the user choice to the corresponding entry implementation

	MenuInterface <|.. MenuFormatter : implements

	EntryService --> GameCollectionDao : uses GamesCollectionDao to access or modify games
	MenuEntry --|> MenuInterface : uses formatter to display

	AddGameService --> HistoryDao : log l'ajout
	RemoveGameService --> HistoryDao : log le retrait
	RecommendOneGameService --> RecommendationStrategy : uses a recommendation strategy
	SummaryService --> RecommendationStrategy : uses a recommendation strategy
	UndoLastActionService --> HistoryDao : register undo of last action

	Command <|.. RemoveGameCommand
	Command <|.. AddGameCommand
	Command --> GameCollectionDao : saves undo actions on the DAO

	RecommendationStrategy <|.. FirstNElementsStrategy
	RecommendationStrategy <|.. LastNElementsStrategy
	RecommendationStrategy <|.. RandomNElementsStrategy
	RecommendationStrategy --> GameCollectionDao : uses

	TournamentFormat <|.. KingOfTheHillFormat : implements
	TournamentFormat <|.. ChampionshipFormat : implements

	Result <|.. Success : implements
    Result <|.. Failure : implements

	EntryService <|.. UndoLastActionService : implements
	EntryService <|.. AddGameService : implements
	EntryService <|.. RemoveGameService : implements
	EntryService <|.. RecommendOneGameService : implements
	EntryService <|.. RecommendByPlayerCountService : implements
	EntryService <|.. ListAllGamesService : implements
	EntryService <|.. SummaryService : implements
	EntryService <|.. TournamentService : implements

	MenuEntry --> EntryService : relays logic to service

	TournamentService --> TournamentFormatFactory : instantiate list of availables formats

	AddGameService --> BoardGameVerificator
	RemoveGameService --> BoardGameVerificator

	TournamentService --> Player : handles players scores and names